apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Deploy to a specific namespace by uncommenting and setting:
# namespace: airgap-architect

resources:
  - base

# Uncomment the following lines to include OpenShift Routes:
# - openshift/route-backend.yaml
# - openshift/route-frontend.yaml
