apiVersion: v1
kind: Service
metadata:
  name: oaa-backend
  labels:
    app: oaa-backend
spec:
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
      name: http
  selector:
    app: oaa-backend
