apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: oaa-frontend
  labels:
    app: oaa-frontend
spec:
  source:
    type: Git
    git:
      uri: https://github.com/bstrauss84/openshift-airgap-architect.git
      ref: fix/openshift-deployment
    contextDir: frontend
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Containerfile
  output:
    to:
      kind: ImageStreamTag
      name: oaa-frontend:latest
  runPolicy: Serial
