/**
 * OpenShift Airgap Architect - IDMS/ITMS Parser
 *
 * Parses ImageDigestMirrorSet and ImageTagMirrorSet YAML files generated by oc-mirror.
 * Extracts mirror sources for install-config.yaml imageDigestSources field.
 *
 * @author Bill Strauss
 *
 * Developed with AI assistance from Claude (Anthropic) and Cursor AI.
 */

import fs from 'node:fs';
import yaml from 'js-yaml';
import logger from './logger.js';

/**
 * Parses IDMS (ImageDigestMirrorSet) YAML file and extracts mirror sources.
 *
 * IDMS format:
 * ```yaml
 * apiVersion: config.openshift.io/v1
 * kind: ImageDigestMirrorSet
 * metadata:
 *   name: oc-mirror
 * spec:
 *   imageDigestMirrors:
 *     - source: quay.io/openshift-release-dev/ocp-release
 *       mirrors:
 *         - registry.example.com:8443/openshift/release
 * ```
 *
 * @param {string} filePath - Path to IDMS YAML file
 * @returns {Array<{source: string, mirrors: string[]}>} Array of mirror sources
 */
export function parseIdmsFile(filePath) {
  if (!filePath) return [];

  try {
    const raw = fs.readFileSync(filePath, 'utf8');
    const doc = yaml.load(raw);

    if (doc?.kind !== 'ImageDigestMirrorSet') {
      logger.warn({ tag: 'startup', filePath, kind: doc?.kind }, 'IDMS file is not ImageDigestMirrorSet kind');
      return [];
    }

    const mirrors = doc?.spec?.imageDigestMirrors;
    if (!Array.isArray(mirrors)) {
      logger.warn({ tag: 'startup', filePath }, 'IDMS file has no spec.imageDigestMirrors array');
      return [];
    }

    const sources = mirrors.map(m => ({
      source: m.source,
      mirrors: Array.isArray(m.mirrors) ? m.mirrors : []
    }));

    logger.info({ tag: 'startup', filePath, count: sources.length }, 'Parsed IDMS file successfully');
    return sources;
  } catch (err) {
    if (err.code === 'ENOENT') {
      logger.warn({ tag: 'startup', filePath }, 'IDMS file not found');
    } else if (err instanceof yaml.YAMLException) {
      logger.warn({ tag: 'startup', err: err.message, filePath }, 'IDMS file is not valid YAML');
    } else {
      logger.warn({ tag: 'startup', err, filePath }, 'Failed to parse IDMS file');
    }
    return [];
  }
}

/**
 * Parses ITMS (ImageTagMirrorSet) YAML file and extracts mirror sources.
 *
 * ITMS format:
 * ```yaml
 * apiVersion: config.openshift.io/v1
 * kind: ImageTagMirrorSet
 * metadata:
 *   name: oc-mirror
 * spec:
 *   imageTagMirrors:
 *     - source: registry.redhat.io/...
 *       mirrors:
 *         - registry.example.com:8443/...
 * ```
 *
 * @param {string} filePath - Path to ITMS YAML file
 * @returns {Array<{source: string, mirrors: string[]}>} Array of mirror sources
 */
export function parseItmsFile(filePath) {
  if (!filePath) return [];

  try {
    const raw = fs.readFileSync(filePath, 'utf8');
    const doc = yaml.load(raw);

    if (doc?.kind !== 'ImageTagMirrorSet') {
      logger.warn({ tag: 'startup', filePath, kind: doc?.kind }, 'ITMS file is not ImageTagMirrorSet kind');
      return [];
    }

    const mirrors = doc?.spec?.imageTagMirrors;
    if (!Array.isArray(mirrors)) {
      logger.warn({ tag: 'startup', filePath }, 'ITMS file has no spec.imageTagMirrors array');
      return [];
    }

    const sources = mirrors.map(m => ({
      source: m.source,
      mirrors: Array.isArray(m.mirrors) ? m.mirrors : []
    }));

    logger.info({ tag: 'startup', filePath, count: sources.length }, 'Parsed ITMS file successfully');
    return sources;
  } catch (err) {
    if (err.code === 'ENOENT') {
      logger.warn({ tag: 'startup', filePath }, 'ITMS file not found');
    } else if (err instanceof yaml.YAMLException) {
      logger.warn({ tag: 'startup', err: err.message, filePath }, 'ITMS file is not valid YAML');
    } else {
      logger.warn({ tag: 'startup', err, filePath }, 'Failed to parse ITMS file');
    }
    return [];
  }
}

/**
 * Loads mirror sources from IDMS and ITMS files.
 * Combines both into a single array of sources.
 *
 * @param {string} idmsPath - Path to IDMS YAML file (optional)
 * @param {string} itmsPath - Path to ITMS YAML file (optional)
 * @returns {Array<{source: string, mirrors: string[]}>} Combined array of mirror sources
 */
export function loadMirrorSources(idmsPath, itmsPath) {
  const idmsSources = parseIdmsFile(idmsPath);
  const itmsSources = parseItmsFile(itmsPath);

  const combined = [...idmsSources, ...itmsSources];

  if (combined.length > 0) {
    logger.info({ tag: 'startup', idmsCount: idmsSources.length, itmsCount: itmsSources.length, total: combined.length }, 'Loaded mirror sources from IDMS/ITMS files');
  }

  return combined;
}
